services:
  - type: web
    name: react-frontend
    env: static
    staticPublishPath: client/build
    buildCommand: cd client && npm install && npm run build

  - type: web
    name: express-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: node server/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-mysql-db
          property: connectionString
